### ISSUE TITLE
Can't install from scratch

### ISSUE THREAD

**Issue by oculos** [nextcloud/calendar_resource_management#113]
### Steps to reproduce

I realized that the calendar application wasn't finding the rooms. So I deleted the application. I also deleted its tables.
When installing the application again, I can't create resources anymore, as the app doesn't recreate the table: 

```
Could not create entry: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: oc_calresources_buildings

```
How can I reinstall the app in a way that it recreates the tables?

### Expected behavior

The app would recreate its tables

### Actual behavior

The app is not working without the tables

### App version

0.7.0

**Comment by st3iny** [comment]
It doesn't run migrations again to create tables because you deleted the tables without deleting migrations.

Please delete all entries on `oc_migrations` where the app name matches the one you deleted all tables of.

E.g. `delete from oc_migrations where app = 'calendar_resource_management';`

Enabling or reinstalling the app afterwards should trigger migrations and recreate tables.

**Comment by oculos** [comment]
Thanks a lot.

It did recreate the tables, but it didn’t populate the calendar tables:

sqlite> select * from oc_calendar_resources;
sqlite> select * from oc_calendar_resources_md;
sqlite> select * from oc_calendar_rooms;
oc_calendar_rooms     oc_calendar_rooms_md
sqlite> select * from oc_calendar_rooms;
sqlite> select * from oc_calendar_rooms_md;

So no room is showing up - I even ran `cron.php` manually to see if that was it.

Anything I can do here?

Best,

Francis

**Comment by st3iny** [comment]
Those tables are created by migrations in the server (apps/dav) and deleting those tables is kind of dangerous.

The simplest path would be to delete and run all migrations of the dav app again. But I'm not sure whether they all are idempotent and you might run into problems when running them again due to existing tables/data.

Or you could dig through all migrations inside `server/apps/dav/lib/Migration/*.php` and manually check which modify the `*_rooms_*` and `*_resources_*` tables. Only those migrations would need to be deleted and triggered again.

I'm very sorry but you are on your own here. Deleting database tables, especially core ones, is not supported and dangerous.

**Comment by oculos** [comment]
> On 10 May 2024, at 12:57, Richard Steinmetz ***@***.***> wrote:
> 
> 
> Those tables are created by migrations in the server (apps/dav) and deleting those tables is kind of dangerous.
> 
> The simplest path would be to delete and run all migrations of the dav app again. But I'm not sure whether they all are idempotent and you might run into problems when running them again due to existing tables/data.
> 
> Or you could dig through all migrations inside server/apps/dav/lib/Migration/*.php and manually check which modify the *_rooms_* and *_resources_* tables. Only those migrations would need to be deleted and triggered again.
> 
> I'm very sorry but you are on your own here. Deleting database tables, especially core ones, is not supported and dangerous.
> 

I am sorry, but “You are own your own” sounds like a lazy answer. I didn’t delete core tables. I deleted tables from _this_application.  If the application doesn’t have a way to remediate itself, it’s a pity.
