### ISSUE TITLE
no view for existing resources

### ISSUE THREAD

**Issue by mokkin** [nextcloud/calendar_resource_management#16]
I managed it finally to activate the app, create building, story and some rooms. I can even search and add those resources in the participants dialogue while adding an appointment.
Unfortunately the resources are not displayed in the calendar menu nor are they visible via CalDAV by third party software such as Thunderbird or an appointment booking system.

![grafik](https://user-images.githubusercontent.com/2938748/139502924-a58c412a-6a8e-4b98-b881-f4cc7e5af6b4.png)

**Comment by ChristophWurst** [comment]
The left sidebar in Calendar only shows *calendars*. A calendar is not a resource.

For Thunderbird I can't tell if they actually support this. A quick internet search gives me the impression Thunderbird/Lightning is simply unable to work with any CalDAV resources. This is not a back-end issue.

**Comment by mokkin** [comment]
Just for understanding: Can you tell how can a user view the resources then in Calendar if they are not displayed like a calendar?

**Comment by ChristophWurst** [comment]
What do you mean? How do you *display* a resource? Do you want to see its availability? More infos about the resource? Anything else?

**Comment by ChristophWurst** [comment]
I think you're referring to a feature like this https://github.com/nextcloud/calendar/issues/3185

**Comment by ChristophWurst** [comment]
FYI I've tested Nextcloud CalDAV resources with Thunderbird. They work if you know their email address. Free/busy overview shows when the resource is already taken. It's not possible to *find* resources, though. I assume this is a limitation of Thunderbird's resource implementation.

**Comment by manu-p** [comment]
Hi, maybe one way to solve this point is:

1. create a NC **Contacts** group named _Resources_
2. create entries in this group, such as for instance "Meeting Room 1" with the email address you've used when creating this room resource with calendar_resource_management
3. in T-Bird, install, setup and use the "[Provider pour CalDAV & CardDAV](https://github.com/jobisoft/DAV-4-TbSync/)" extension
4. after a while (until NC Contacts are synchronized with your T-Bird) you should find the _Resources_ group (here named Category) in the Contacts...

**Comment by ChristophWurst** [comment]
That's an interesting idea!

**Comment by e-jim** [comment]
Just for reference, we achieved to share the calendar (similarly to @mokkin 's request) by manually adding a caldav share in database.
Not sure if it's a good idea regarding future update or whether Sabre likes it, but in test environment it seemed to work.

Here is what we did:

`SELECT * from oc_calendars WHERE oc_calendars.principaluri LIKE "%resource%"; `

to find the id of the resource calendar we want to share

`INSERT INTO oc_dav_shares(principaluri, type, access, resourceid) VALUES ("principals/groups/MyGroup", "calendar", 3, ID); `

Replace:
-  "principals/groups/MyGroup" by the group or user (principals/user) you want to share it with
-  3 by 2 if you want the share to be write-enabled instead of read-only (I also tested access 4, which is used for public URI and allows re-sharing - not sure it
- ID by the id of the resource you found in the first step

Use a your own risks ;-)

**Comment by tatrapikao** [comment]
how on earth ist his closed?
