### ISSUE TITLE
Vehicle resource

### ISSUE THREAD

**Issue by manu-p** [nextcloud/calendar_resource_management#20]
Hi, 

There's a mistake in the order of parameters in calendar-resource:vehicle:create as show in README.md.
It is written:
> uid* building_id* display_name* email* contact_person_user_id* vehicle_type* vehicle_make* vehicle_model* is_electric range seating_capacity

But it is:
> uid* building_id* display_name* email* vehicle_type* vehicle_make* vehicle_model* is_electric range seating_capacity contact_person_user_id* 

If I understand well, it just needs to create a building, and then create a vehicle attached to the building. OK.
Then I read:
> The resources will be added to the calendar app via cron.

Which crontab? Didn't find anything in www-data crontab, nor in any other /etc/cron.* directories.
In other words, how long does it take to let users choose the new vehicle as a resource?

I can see it is populated in the oc_calresources_vehicles table, is there anything else to do to "publish" this resource?

**Comment by manu-p** [comment]
I give the answer I found somewhere else.
> The resources will be added to the calendar app via cron.

It's cron.php in the crontab of www-data or whatever user is used for the web server (apache2, nginx, ...)

**Comment by ChristophWurst** [comment]
Indeed. It's a background job in Nextcloud https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html

**Comment by sh3d0w94** [comment]
I see the resource room in my nextcloud calender. 
But i didn't see the vehicle resources. 
Where can I select these and add them to my appointment?

LG

**Comment by marneu** [comment]
May I second the request, where can I add a pool car to a calender event?

**Comment by st3iny** [comment]
Regarding the readme: This has been solved in the meantime and the readme was adjusted.

Regarding the vehicle: I just created a vehicle and am able to find it by its display name in the resource tab after adding it. Please keep in mind that the cron job has to run at least once after adding a resource/vehicle. That can take up to an hour.

I'm closing this issue because the original issue has been solved. Please open a new issue if you discover a bug or have feedback.
