### ISSUE TITLE
Update for 24 and release to app store

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/calendar_resource_management#61]
### Is your feature request related to a problem? Please describe.

empty non-nextcloud maintainer owned store entry for calendar_resource_management

### Describe the solution you'd like

replace app store presence and release for 24, see https://apps.nextcloud.com/apps/calendar_resource_management

### Describe alternatives you've considered

no other available

**Comment by ChristophWurst** [comment]
https://apps.nextcloud.com/apps/calendar_resource_management was registered as *integration* by "Danir Toma".

The app is compatible up to Nextcloud 25 since https://github.com/nextcloud/calendar_resource_management/pull/50.
https://github.com/nextcloud/calendar_resource_management/issues/14 is the ticket to track app store releasing.

**Comment by ChristophWurst** [comment]
Let's continue in the existing ticket.

**Comment by nickvergessen** [comment]
Integration was removed
